name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # #nodejs-suppport
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --immutable --immutable-cache
      - name: Check Yarn cache
        # Only run on forks
        if: github.repository_owner != 'eps1lon'
        run: yarn --check-cache
      - run: yarn test:unit
      - run: yarn test:lint
      - run: yarn test:types
      - run: yarn format:check
      - run: yarn test:renovate
      # for manual inspection of included files
      - run: npm pack
